version: '3'
services:
  frontend:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0

  orchestrator:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
      - MONGO_URI=mongodb://admin:password@mongodb:27017/bookstore
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src
  
  # fraud_detection:
  #   platform: linux/arm64
  #   build:
  #     context: ./
  #     dockerfile: ./fraud_detection/Dockerfile
  #   ports:
  #     - 50051:50051
  #   environment:
  #     - PYTHONUNBUFFERED=TRUE
  #     - PYTHONFILE=/app/fraud_detection/src/app.py
  #   volumes:
  #     - ./utils:/app/utils
  #     - ./fraud_detection/src:/app/fraud_detection/src

  # transaction_verification:
  #   platform: linux/arm64
  #   build:
  #     context: ./
  #     dockerfile: ./transaction_verification/Dockerfile
  #   ports:
  #     - 50052:50052
  #   environment:
  #     - PYTHONUNBUFFERED=TRUE
  #     - PYTHONFILE=/app/transaction_verification/src/app.py
  #   volumes:
  #     - ./utils:/app/utils
  #     - ./transaction_verification/src:/app/transaction_verification/src

  # suggestions:
  #   platform: linux/arm64
  #   build:
  #     context: ./
  #     dockerfile: ./suggestions/Dockerfile
  #   ports:
  #     - 50053:50053
  #   environment:
  #     - PYTHONUNBUFFERED=TRUE
  #     - PYTHONFILE=/app/suggestions/src/app.py
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/bookstore
  #   volumes:
  #     - ./utils:/app/utils
  #     - ./suggestions/src:/app/suggestions/src

  # book_suggestion_model:
  #   platform: linux/arm64
  #   build:
  #     context: ./
  #     dockerfile: ./book_suggestion_model/Dockerfile
  #   ports:
  #     - 50054:50054
  #   environment:
  #     - PYTHONUNBUFFERED=TRUE
  #     - PYTHONFILE=/app/book_suggestion_model/src/app.py
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/bookstore
  #   volumes:
  #     - ./utils:/app/utils
  #     - ./book_suggestion_model/src:/app/book_suggestion_model/src

  # ---- order processing ----
  order_queue:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./order_queue/Dockerfile
    ports:
      - 50055:50055
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_queue/src/app.py
      - MONGO_URI=mongodb://admin:password@mongodb:27017/bookstore
    volumes:
      - ./utils:/app/utils
      - ./order_queue/src:/app/order_queue/src


  order_executor_1:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    ports:
      - "50056:50056"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_executor/src/app.py
      - MONGO_URI=mongodb://admin:password@mongodb:27017/bookstore
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVICE_ID=order_executor_1
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src


  # ---- books database ----
  book_storage_1:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./book_storage/Dockerfile
    ports:
      - "50060:50060"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/book_storage/src/app.py
      - MONGO_URI=mongodb://admin:password@mongodb:27017/bookstore
      - ZK_HOSTS=zookeeper:2181
      - SERVICE_ID=book_storage_1
    volumes:
      - ./utils:/app/utils
      - ./book_storage/src:/app/book_storage/src

    
  book_storage_2:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./book_storage/Dockerfile
    ports:
      - "50061:50060"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/book_storage/src/app.py
      - MONGO_URI=mongodb://admin:password@mongodb:27017/bookstore
      - ZK_HOSTS=zookeeper:2181
      - SERVICE_ID=book_storage_2
    volumes:
      - ./utils:/app/utils
      - ./book_storage/src:/app/book_storage/src


  book_storage_3:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./book_storage/Dockerfile
    ports:
      - "50062:50060"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/book_storage/src/app.py
      - MONGO_URI=mongodb://admin:password@mongodb:27017/bookstore
      - ZK_HOSTS=zookeeper:2181
      - SERVICE_ID=book_storage_3
    volumes:
      - ./utils:/app/utils
      - ./book_storage/src:/app/book_storage/src


  zookeeper:
    image: zookeeper:3.5
    ports:
      - "2181:2181"



  # ---- databases ----
  # https://gist.github.com/gbzarelli/c15b607d62fc98ae436564bf8129ea8e
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: bookstore
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init_scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  # mongodb_users:
  #   container_name: mongodb_users
  #   image: mongo:latest
  #   restart: always
  #   environment:
  #     MONGO_INITDB_DATABASE: users
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongodb_users_data:/data/db
  #   ports:
  #     - "27018:27017"

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "8099:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     # ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_PORT: 27017
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    
    
volumes:
  mongodb_data:
  mongodb_users_data:


networks:
  app_network:
    driver: bridge