# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.book_suggestion_model import book_suggestion_model_pb2 as utils_dot_pb_dot_book__suggestion__model_dot_book__suggestion__model__pb2


class BookSuggestionModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookRecommendations = channel.unary_unary(
                '/booksuggestion.BookSuggestionModelService/GetBookRecommendations',
                request_serializer=utils_dot_pb_dot_book__suggestion__model_dot_book__suggestion__model__pb2.RecommendationsRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__suggestion__model_dot_book__suggestion__model__pb2.BookRecommendations.FromString,
                )


class BookSuggestionModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookSuggestionModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookRecommendations,
                    request_deserializer=utils_dot_pb_dot_book__suggestion__model_dot_book__suggestion__model__pb2.RecommendationsRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__suggestion__model_dot_book__suggestion__model__pb2.BookRecommendations.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booksuggestion.BookSuggestionModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookSuggestionModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/booksuggestion.BookSuggestionModelService/GetBookRecommendations',
            utils_dot_pb_dot_book__suggestion__model_dot_book__suggestion__model__pb2.RecommendationsRequest.SerializeToString,
            utils_dot_pb_dot_book__suggestion__model_dot_book__suggestion__model__pb2.BookRecommendations.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
