# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\x0border_queue\"9\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\norder_json\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\"\"\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0e\x44\x65queueRequest2\x90\x01\n\x11OrderQueueService\x12=\n\x07\x45nqueue\x12\x12.order_queue.Order\x1a\x1c.order_queue.EnqueueResponse\"\x00\x12<\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x12.order_queue.Order\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=55
  _globals['_ORDER']._serialized_end=112
  _globals['_ENQUEUERESPONSE']._serialized_start=114
  _globals['_ENQUEUERESPONSE']._serialized_end=148
  _globals['_DEQUEUEREQUEST']._serialized_start=150
  _globals['_DEQUEUEREQUEST']._serialized_end=166
  _globals['_ORDERQUEUESERVICE']._serialized_start=169
  _globals['_ORDERQUEUESERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
