# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/transaction_verification/transaction_verification.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@utils/pb/transaction_verification/transaction_verification.proto\x12\x18transaction_verification\"4\n\x1eTransactionVerificationRequest\x12\x12\n\norder_json\x18\x01 \x01(\t\"3\n\x1fTransactionVerificationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\xab\x01\n\x1eTransactionVerificationService\x12\x88\x01\n\x11VerifyTransaction\x12\x38.transaction_verification.TransactionVerificationRequest\x1a\x39.transaction_verification.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.transaction_verification.transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_start=94
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_end=146
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=148
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=199
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=202
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
