# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.order_executor import order_executor_pb2 as utils_dot_pb_dot_order__executor_dot_order__executor__pb2


class OrderExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessOrder = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/ProcessOrder',
                request_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ProcessOrderRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ProcessOrderResponse.FromString,
                )


class OrderExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessOrder,
                    request_deserializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ProcessOrderRequest.FromString,
                    response_serializer=utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ProcessOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderexecutor.OrderExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/ProcessOrder',
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ProcessOrderRequest.SerializeToString,
            utils_dot_pb_dot_order__executor_dot_order__executor__pb2.ProcessOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
