# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_executor/order_executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/order_executor/order_executor.proto\x12\rorderexecutor\"\x15\n\x13ProcessOrderRequest\"8\n\x14ProcessOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2q\n\x14OrderExecutorService\x12Y\n\x0cProcessOrder\x12\".orderexecutor.ProcessOrderRequest\x1a#.orderexecutor.ProcessOrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_executor.order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROCESSORDERREQUEST']._serialized_start=63
  _globals['_PROCESSORDERREQUEST']._serialized_end=84
  _globals['_PROCESSORDERRESPONSE']._serialized_start=86
  _globals['_PROCESSORDERRESPONSE']._serialized_end=142
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=144
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
