# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.book_storage import book_storage_pb2 as utils_dot_pb_dot_book__storage_dot_book__storage__pb2


class BookStorageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Write = channel.unary_unary(
                '/book_storage.BookStorage/Write',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.WriteRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.WriteResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/book_storage.BookStorage/Read',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.ReadRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.ReadResponse.FromString,
                )
        self.CleanVersion = channel.unary_unary(
                '/book_storage.BookStorage/CleanVersion',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CleanVersionRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CleanVersionResponse.FromString,
                )
        self.CheckStock = channel.unary_unary(
                '/book_storage.BookStorage/CheckStock',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CheckStockRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CheckStockResponse.FromString,
                )
        self.DecrementStock = channel.unary_unary(
                '/book_storage.BookStorage/DecrementStock',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateResponse.FromString,
                )
        self.IncrementStock = channel.unary_unary(
                '/book_storage.BookStorage/IncrementStock',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateResponse.FromString,
                )
        self.Prepare = channel.unary_unary(
                '/book_storage.BookStorage/Prepare',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.PrepareRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.PrepareResponse.FromString,
                )
        self.Commit = channel.unary_unary(
                '/book_storage.BookStorage/Commit',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CommitRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CommitResponse.FromString,
                )
        self.Abort = channel.unary_unary(
                '/book_storage.BookStorage/Abort',
                request_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.AbortRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.AbortResponse.FromString,
                )


class BookStorageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecrementStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookStorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.WriteRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.WriteResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.ReadRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.ReadResponse.SerializeToString,
            ),
            'CleanVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanVersion,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CleanVersionRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CleanVersionResponse.SerializeToString,
            ),
            'CheckStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStock,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CheckStockRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CheckStockResponse.SerializeToString,
            ),
            'DecrementStock': grpc.unary_unary_rpc_method_handler(
                    servicer.DecrementStock,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateResponse.SerializeToString,
            ),
            'IncrementStock': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementStock,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateResponse.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.PrepareRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.PrepareResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CommitRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CommitResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.AbortRequest.FromString,
                    response_serializer=utils_dot_pb_dot_book__storage_dot_book__storage__pb2.AbortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'book_storage.BookStorage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookStorage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/Write',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.WriteRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/Read',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.ReadRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CleanVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/CleanVersion',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CleanVersionRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CleanVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/CheckStock',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CheckStockRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CheckStockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DecrementStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/DecrementStock',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IncrementStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/IncrementStock',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.StockUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/Prepare',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.PrepareRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.PrepareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/Commit',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CommitRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.CommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/book_storage.BookStorage/Abort',
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.AbortRequest.SerializeToString,
            utils_dot_pb_dot_book__storage_dot_book__storage__pb2.AbortResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
