{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Orchestrator traces",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "ff049930", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "orchestrator" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [
        "process_orders",
        "enqueue_order"
       ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  { "title": "Histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Duration of request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestrator_duration_ms_milliseconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration of books suggestions by model",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "suggestion_creation_duration_milliseconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "UpDownCounter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Active orders order_executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "order_executor_active_orders", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orders in queue ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "order_queue_items", "legendFormat": "__auto" }
   ]
  },
  { "title": "Counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Approved/Rejected Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "orchestrator_order_rejected_count_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "orchestrator_order_approved_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gause", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage order_executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "order_executor_cpu_usage_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage Book Suggestions Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "memory_usage_MB", "legendFormat": "__auto" }
   ]
  }
 ]
}