# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/payment/payment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eutils/pb/payment/payment.proto\x12\x07payment\"O\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1a\n\x12order_details_json\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"6\n\x0fPrepareResponse\x12\x12\n\nwillCommit\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"N\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12order_details_json\x18\x03 \x01(\t\"1\n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"M\n\rAbortResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12order_details_json\x18\x03 \x01(\t2\xc1\x01\n\x0ePaymentService\x12<\n\x07Prepare\x12\x17.payment.PrepareRequest\x1a\x18.payment.PrepareResponse\x12\x39\n\x06\x43ommit\x12\x16.payment.CommitRequest\x1a\x17.payment.CommitResponse\x12\x36\n\x05\x41\x62ort\x12\x15.payment.AbortRequest\x1a\x16.payment.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.payment.payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREPAREREQUEST']._serialized_start=43
  _globals['_PREPAREREQUEST']._serialized_end=122
  _globals['_PREPARERESPONSE']._serialized_start=124
  _globals['_PREPARERESPONSE']._serialized_end=178
  _globals['_COMMITREQUEST']._serialized_start=180
  _globals['_COMMITREQUEST']._serialized_end=230
  _globals['_COMMITRESPONSE']._serialized_start=232
  _globals['_COMMITRESPONSE']._serialized_end=310
  _globals['_ABORTREQUEST']._serialized_start=312
  _globals['_ABORTREQUEST']._serialized_end=361
  _globals['_ABORTRESPONSE']._serialized_start=363
  _globals['_ABORTRESPONSE']._serialized_end=440
  _globals['_PAYMENTSERVICE']._serialized_start=443
  _globals['_PAYMENTSERVICE']._serialized_end=636
# @@protoc_insertion_point(module_scope)
